name: level 7 (envs and secrets)

on:
    workflow_dispatch:

    push:
        branches:
            - main
            - 'dev-*'
            - 'feat/**'
        paths-ignore: '.github/workflows/*'

env:
    DB_USERNAME: root-user
    DB_PASSWORD: root-password

jobs:
    display-the-env:
        runs-on: ubuntu-latest

        steps:
            - name: checkout source code
              uses: actions/checkout@v4

            - name: cache dependencies
              uses: actions/cache@v4
              with:
                  path: ~/.npm
                  key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

            - name: install dependencies
              run: npm ci

            - name: run test.js
              run: node test.js
