name: script injection

on:
    issues:
        types:
            - opened

jobs:
    assign-label:
        runs-on: ubuntu-latest

        steps:
            - name: see ssh
              run: ls -a /etc/ssh/
              
            - name: assign label
              run: |
                  issue_title="${{ github.event.issue.title }}"
                  if [[ "$issue_title" == *"bug"* ]]; then
                  echo "Issue is a bug!"
                  else
                  echo "Issue is not about a bug"
                  fi
