name: Level-4 (activity types, filters, and protections)

on:
  pull_request:
    types: [opened, edited]
    branches:
      - main
  workflow_dispatch:
  push:
    branches:
      - main
      - 'dev-*'
      - 'feat/**'
    # paths:
    #   - '**.js'
    #   - '**.md'
    paths-ignore:
      '.github/workflows/*'


jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: PR just happened
        run: echo "A NEW PR WAS JUST OPENED...!"
